services:
  # Service PHP
  php:
    build:
      context: .  # Indique le répertoire où Docker peut trouver ton Dockerfile. Ici, c'est le répertoire actuel.
      dockerfile: Dockerfile  # Assure-toi que le nom du Dockerfile est correct, ici "Dockerfile" en minuscules.
    container_name: php83  # Donne un nom personnalisé au conteneur, ici "php83".
    image: php:8.3-apache  # Définit l'image de base à utiliser (PHP 8.3 avec Apache).
    ports:
      - "8090:80"  # Mappe le port 8090 de la machine hôte vers le port 80 du conteneur. Accéder à l'application Symfony via http://localhost:8090.
    volumes:
      - .:/var/www/html  # Monte le répertoire courant (contenant le code source) vers /var/www/html dans le conteneur.
      - ./my-apache-config.conf:/etc/apache2/sites-available/000-default.conf  # Remplace la configuration Apache par un fichier personnalisé.
    depends_on:
      - db  # Ce service dépend du service "db" (la base de données), donc PHP attendra que la base soit prête avant de démarrer.
    networks:
      - symfony_network  # Connecte ce service au réseau "symfony_network" pour la communication avec d'autres services.
  # Service MySQL (base de données)
  
  db:
    image: mysql:8.0  # Utilise l'image officielle de MySQL version 8.0.
    container_name: mysql83  # Nom du conteneur MySQL.
    environment:
      MYSQL_ROOT_PASSWORD: pass  # Définie le mot de passe pour l'utilisateur "root" de MySQL.
      MYSQL_DATABASE: demo  # Crée une base de données nommée "demo".
      MYSQL_USER: test  # Crée un utilisateur nommé "test".
      MYSQL_PASSWORD: pass  # Définit le mot de passe pour l'utilisateur "test".
    ports:
      - "3307:3306"  # Mappe le port 3307 de l'hôte au port 3306 du conteneur (port par défaut de MySQL).
    networks:
      - symfony_network  # Connecte ce service au même réseau "symfony_network" pour qu'il soit accessible par les autres services.
  # Service PhpMyAdmin (interface graphique pour MySQL)
  phpma:
    image: phpmyadmin/phpmyadmin  # Utilise l'image officielle de PhpMyAdmin.
    container_name: phpmyadmin  # Nom du conteneur PhpMyAdmin.
    environment:
      PMA_HOST: db  # Indique que PhpMyAdmin doit se connecter à la base de données "db".
      PMA_USER: root  # Utilise l'utilisateur "root" pour se connecter à MySQL.
      PMA_PASSWORD: pass  # Le mot de passe de l'utilisateur "root".
    ports:
      - "8899:80"  # Mappe le port 8899 de l'hôte vers le port 80 du conteneur PhpMyAdmin. Accède à PhpMyAdmin via http://localhost:8899.
    networks:
      - symfony_network  # Connecte ce service au même réseau "symfony_network" pour qu'il puisse communiquer avec la base de données et PHP.
# Réseaux
networks:
  symfony_network:
    driver: bridge  # Utilisation du réseau "bridge", qui est le mode par défaut pour la communication entre conteneurs.
