<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQTwWh2t\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQTwWh2t/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQTwWh2t.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQTwWh2t\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQTwWh2t\App_KernelProdContainer([
    'container.build_hash' => 'QTwWh2t',
    'container.build_id' => '2aca7b1d',
    'container.build_time' => 1752678247,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQTwWh2t');
