<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class JourHoraire extends \App\Entity\JourHoraire implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'datePrecise' => [parent::class, 'datePrecise', null],
        "\0".parent::class."\0".'heureDebut' => [parent::class, 'heureDebut', null],
        "\0".parent::class."\0".'heureFin' => [parent::class, 'heureFin', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'jour' => [parent::class, 'jour', null],
        "\0".parent::class."\0".'utilisateurinstitutionsessionmodule' => [parent::class, 'utilisateurinstitutionsessionmodule', null],
        'datePrecise' => [parent::class, 'datePrecise', null],
        'heureDebut' => [parent::class, 'heureDebut', null],
        'heureFin' => [parent::class, 'heureFin', null],
        'id' => [parent::class, 'id', null],
        'jour' => [parent::class, 'jour', null],
        'utilisateurinstitutionsessionmodule' => [parent::class, 'utilisateurinstitutionsessionmodule', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
