<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FormContact extends \App\Entity\FormContact implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Dates' => [parent::class, 'Dates', null],
        "\0".parent::class."\0".'Email' => [parent::class, 'Email', null],
        "\0".parent::class."\0".'Nom' => [parent::class, 'Nom', null],
        "\0".parent::class."\0".'NomInstitution' => [parent::class, 'NomInstitution', null],
        "\0".parent::class."\0".'NomModule' => [parent::class, 'NomModule', null],
        "\0".parent::class."\0".'NomSession' => [parent::class, 'NomSession', null],
        "\0".parent::class."\0".'Prenom' => [parent::class, 'Prenom', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'message' => [parent::class, 'message', null],
        "\0".parent::class."\0".'offre' => [parent::class, 'offre', null],
        'Dates' => [parent::class, 'Dates', null],
        'Email' => [parent::class, 'Email', null],
        'Nom' => [parent::class, 'Nom', null],
        'NomInstitution' => [parent::class, 'NomInstitution', null],
        'NomModule' => [parent::class, 'NomModule', null],
        'NomSession' => [parent::class, 'NomSession', null],
        'Prenom' => [parent::class, 'Prenom', null],
        'id' => [parent::class, 'id', null],
        'message' => [parent::class, 'message', null],
        'offre' => [parent::class, 'offre', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
