<?php

namespace ContainerRxXGSEN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AUTFbYRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AUTFbYR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AUTFbYR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\AccueilController::index' => ['privates', '.service_locator.ZmozSE3.App\\Controller\\AccueilController::index()', 'getAccueilControllerindexService', true],
            'App\\Controller\\CalendrierController::voirCalendrier' => ['privates', '.service_locator.0pJot0q.App\\Controller\\CalendrierController::voirCalendrier()', 'getCalendrierControllervoirCalendrierService', true],
            'App\\Controller\\ConnexionController::connexion' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\ConnexionController::connexion()', 'getConnexionControllerconnexionService', true],
            'App\\Controller\\InscriptionController::register' => ['privates', '.service_locator.tCJ8qfZ.App\\Controller\\InscriptionController::register()', 'getInscriptionControllerregisterService', true],
            'App\\Controller\\InstitutionController::indexEtAjouter' => ['privates', '.service_locator.MFcjO6b.App\\Controller\\InstitutionController::indexEtAjouter()', 'getInstitutionControllerindexEtAjouterService', true],
            'App\\Controller\\InstitutionController::liste' => ['privates', '.service_locator.GsSF5aC.App\\Controller\\InstitutionController::liste()', 'getInstitutionControllerlisteService', true],
            'App\\Controller\\InstitutionController::modifierRoles' => ['privates', '.service_locator.0T6sRVU.App\\Controller\\InstitutionController::modifierRoles()', 'getInstitutionControllermodifierRolesService', true],
            'App\\Controller\\InstitutionController::modifier' => ['privates', '.service_locator.6S4WW3N.App\\Controller\\InstitutionController::modifier()', 'getInstitutionControllermodifierService', true],
            'App\\Controller\\InstitutionController::modifiermodulecommentaire' => ['privates', '.service_locator._t01d57.App\\Controller\\InstitutionController::modifiermodulecommentaire()', 'getInstitutionControllermodifiermodulecommentaireService', true],
            'App\\Controller\\InvitationController::invite' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\InvitationController::invite()', 'getInvitationControllerinviteService', true],
            'App\\Controller\\InvitationController::acceptInvitation' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\InvitationController::acceptInvitation()', 'getInvitationControlleracceptInvitationService', true],
            'App\\Controller\\PDF_Envoie_Mail::handlePdfRequest' => ['privates', '.service_locator.1483v_I.App\\Controller\\PDF_Envoie_Mail::handlePdfRequest()', 'getPDFEnvoieMailhandlePdfRequestService', true],
            'App\\Controller\\PDF_Envoie_Mail::envoiSessionPdfs' => ['privates', '.service_locator.Js4HdLW.App\\Controller\\PDF_Envoie_Mail::envoiSessionPdfs()', 'getPDFEnvoieMailenvoiSessionPdfsService', true],
            'App\\Controller\\PDF_Envoie_Mail::envoiToutPdfs' => ['privates', '.service_locator.qqJ6CEo.App\\Controller\\PDF_Envoie_Mail::envoiToutPdfs()', 'getPDFEnvoieMailenvoiToutPdfsService', true],
            'App\\Controller\\SessionModuleController::index' => ['privates', '.service_locator..Vj_0Fk.App\\Controller\\SessionModuleController::index()', 'getSessionModuleControllerindexService', true],
            'App\\Controller\\SessionModuleController::modifierSessionModule' => ['privates', '.service_locator.LceDNDN.App\\Controller\\SessionModuleController::modifierSessionModule()', 'getSessionModuleControllermodifierSessionModuleService', true],
            'App\\Controller\\SessionModuleController::modifierUtilisateurInstitutionSessionModule' => ['privates', '.service_locator.Za3h8vK.App\\Controller\\SessionModuleController::modifierUtilisateurInstitutionSessionModule()', 'getSessionModuleControllermodifierUtilisateurInstitutionSessionModuleService', true],
            'App\\Controller\\SessionModuleController::modifierSession' => ['privates', '.service_locator.ynbETY9.App\\Controller\\SessionModuleController::modifierSession()', 'getSessionModuleControllermodifierSessionService', true],
            'App\\Controller\\SessionModuleController::modifierInstitution' => ['privates', '.service_locator.6pPFRks.App\\Controller\\SessionModuleController::modifierInstitution()', 'getSessionModuleControllermodifierInstitutionService', true],
            'App\\Controller\\SessionModuleController::modifierModule' => ['privates', '.service_locator.zdlRbJD.App\\Controller\\SessionModuleController::modifierModule()', 'getSessionModuleControllermodifierModuleService', true],
            'App\\Controller\\StripeController::reussite' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\StripeController::reussite()', 'getStripeControllerreussiteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\AccueilController:index' => ['privates', '.service_locator.ZmozSE3.App\\Controller\\AccueilController::index()', 'getAccueilControllerindexService', true],
            'App\\Controller\\CalendrierController:voirCalendrier' => ['privates', '.service_locator.0pJot0q.App\\Controller\\CalendrierController::voirCalendrier()', 'getCalendrierControllervoirCalendrierService', true],
            'App\\Controller\\ConnexionController:connexion' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\ConnexionController::connexion()', 'getConnexionControllerconnexionService', true],
            'App\\Controller\\InscriptionController:register' => ['privates', '.service_locator.tCJ8qfZ.App\\Controller\\InscriptionController::register()', 'getInscriptionControllerregisterService', true],
            'App\\Controller\\InstitutionController:indexEtAjouter' => ['privates', '.service_locator.MFcjO6b.App\\Controller\\InstitutionController::indexEtAjouter()', 'getInstitutionControllerindexEtAjouterService', true],
            'App\\Controller\\InstitutionController:liste' => ['privates', '.service_locator.GsSF5aC.App\\Controller\\InstitutionController::liste()', 'getInstitutionControllerlisteService', true],
            'App\\Controller\\InstitutionController:modifierRoles' => ['privates', '.service_locator.0T6sRVU.App\\Controller\\InstitutionController::modifierRoles()', 'getInstitutionControllermodifierRolesService', true],
            'App\\Controller\\InstitutionController:modifier' => ['privates', '.service_locator.6S4WW3N.App\\Controller\\InstitutionController::modifier()', 'getInstitutionControllermodifierService', true],
            'App\\Controller\\InstitutionController:modifiermodulecommentaire' => ['privates', '.service_locator._t01d57.App\\Controller\\InstitutionController::modifiermodulecommentaire()', 'getInstitutionControllermodifiermodulecommentaireService', true],
            'App\\Controller\\InvitationController:invite' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\InvitationController::invite()', 'getInvitationControllerinviteService', true],
            'App\\Controller\\InvitationController:acceptInvitation' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\InvitationController::acceptInvitation()', 'getInvitationControlleracceptInvitationService', true],
            'App\\Controller\\PDF_Envoie_Mail:handlePdfRequest' => ['privates', '.service_locator.1483v_I.App\\Controller\\PDF_Envoie_Mail::handlePdfRequest()', 'getPDFEnvoieMailhandlePdfRequestService', true],
            'App\\Controller\\PDF_Envoie_Mail:envoiSessionPdfs' => ['privates', '.service_locator.Js4HdLW.App\\Controller\\PDF_Envoie_Mail::envoiSessionPdfs()', 'getPDFEnvoieMailenvoiSessionPdfsService', true],
            'App\\Controller\\PDF_Envoie_Mail:envoiToutPdfs' => ['privates', '.service_locator.qqJ6CEo.App\\Controller\\PDF_Envoie_Mail::envoiToutPdfs()', 'getPDFEnvoieMailenvoiToutPdfsService', true],
            'App\\Controller\\SessionModuleController:index' => ['privates', '.service_locator..Vj_0Fk.App\\Controller\\SessionModuleController::index()', 'getSessionModuleControllerindexService', true],
            'App\\Controller\\SessionModuleController:modifierSessionModule' => ['privates', '.service_locator.LceDNDN.App\\Controller\\SessionModuleController::modifierSessionModule()', 'getSessionModuleControllermodifierSessionModuleService', true],
            'App\\Controller\\SessionModuleController:modifierUtilisateurInstitutionSessionModule' => ['privates', '.service_locator.Za3h8vK.App\\Controller\\SessionModuleController::modifierUtilisateurInstitutionSessionModule()', 'getSessionModuleControllermodifierUtilisateurInstitutionSessionModuleService', true],
            'App\\Controller\\SessionModuleController:modifierSession' => ['privates', '.service_locator.ynbETY9.App\\Controller\\SessionModuleController::modifierSession()', 'getSessionModuleControllermodifierSessionService', true],
            'App\\Controller\\SessionModuleController:modifierInstitution' => ['privates', '.service_locator.6pPFRks.App\\Controller\\SessionModuleController::modifierInstitution()', 'getSessionModuleControllermodifierInstitutionService', true],
            'App\\Controller\\SessionModuleController:modifierModule' => ['privates', '.service_locator.zdlRbJD.App\\Controller\\SessionModuleController::modifierModule()', 'getSessionModuleControllermodifierModuleService', true],
            'App\\Controller\\StripeController:reussite' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\StripeController::reussite()', 'getStripeControllerreussiteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AccueilController::index' => '?',
            'App\\Controller\\CalendrierController::voirCalendrier' => '?',
            'App\\Controller\\ConnexionController::connexion' => '?',
            'App\\Controller\\InscriptionController::register' => '?',
            'App\\Controller\\InstitutionController::indexEtAjouter' => '?',
            'App\\Controller\\InstitutionController::liste' => '?',
            'App\\Controller\\InstitutionController::modifierRoles' => '?',
            'App\\Controller\\InstitutionController::modifier' => '?',
            'App\\Controller\\InstitutionController::modifiermodulecommentaire' => '?',
            'App\\Controller\\InvitationController::invite' => '?',
            'App\\Controller\\InvitationController::acceptInvitation' => '?',
            'App\\Controller\\PDF_Envoie_Mail::handlePdfRequest' => '?',
            'App\\Controller\\PDF_Envoie_Mail::envoiSessionPdfs' => '?',
            'App\\Controller\\PDF_Envoie_Mail::envoiToutPdfs' => '?',
            'App\\Controller\\SessionModuleController::index' => '?',
            'App\\Controller\\SessionModuleController::modifierSessionModule' => '?',
            'App\\Controller\\SessionModuleController::modifierUtilisateurInstitutionSessionModule' => '?',
            'App\\Controller\\SessionModuleController::modifierSession' => '?',
            'App\\Controller\\SessionModuleController::modifierInstitution' => '?',
            'App\\Controller\\SessionModuleController::modifierModule' => '?',
            'App\\Controller\\StripeController::reussite' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AccueilController:index' => '?',
            'App\\Controller\\CalendrierController:voirCalendrier' => '?',
            'App\\Controller\\ConnexionController:connexion' => '?',
            'App\\Controller\\InscriptionController:register' => '?',
            'App\\Controller\\InstitutionController:indexEtAjouter' => '?',
            'App\\Controller\\InstitutionController:liste' => '?',
            'App\\Controller\\InstitutionController:modifierRoles' => '?',
            'App\\Controller\\InstitutionController:modifier' => '?',
            'App\\Controller\\InstitutionController:modifiermodulecommentaire' => '?',
            'App\\Controller\\InvitationController:invite' => '?',
            'App\\Controller\\InvitationController:acceptInvitation' => '?',
            'App\\Controller\\PDF_Envoie_Mail:handlePdfRequest' => '?',
            'App\\Controller\\PDF_Envoie_Mail:envoiSessionPdfs' => '?',
            'App\\Controller\\PDF_Envoie_Mail:envoiToutPdfs' => '?',
            'App\\Controller\\SessionModuleController:index' => '?',
            'App\\Controller\\SessionModuleController:modifierSessionModule' => '?',
            'App\\Controller\\SessionModuleController:modifierUtilisateurInstitutionSessionModule' => '?',
            'App\\Controller\\SessionModuleController:modifierSession' => '?',
            'App\\Controller\\SessionModuleController:modifierInstitution' => '?',
            'App\\Controller\\SessionModuleController:modifierModule' => '?',
            'App\\Controller\\StripeController:reussite' => '?',
        ]);
    }
}
