<?php

namespace ContainerRxXGSEN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstitutionControllermodifierRolesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0T6sRVU.App\Controller\InstitutionController::modifierRoles()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0T6sRVU.App\\Controller\\InstitutionController::modifierRoles()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'utilisateur' => ['privates', 'App\\Entity\\Utilisateur', 'getUtilisateurService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'utilisateur' => 'App\\Entity\\Utilisateur',
            'em' => '?',
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\InstitutionController::modifierRoles()', $container);
    }
}
