<?php

namespace ContainerRxXGSEN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstitutionControllermodifiermodulecommentaireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._t01d57.App\Controller\InstitutionController::modifiermodulecommentaire()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._t01d57.App\\Controller\\InstitutionController::modifiermodulecommentaire()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'utilisateurInstitutionSessionModulesRepository' => ['privates', 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository', 'getUtilisateurInstitutionSessionModuleRepositoryService', true],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'utilisateurInstitutionSessionModulesRepository' => 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
            'em' => '?',
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\InstitutionController::modifiermodulecommentaire()', $container);
    }
}
