<?php

namespace ContainerRxXGSEN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstitutionControllerlisteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GsSF5aC.App\Controller\InstitutionController::liste()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GsSF5aC.App\\Controller\\InstitutionController::liste()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'utilisateur' => ['privates', 'App\\Entity\\Utilisateur', 'getUtilisateurService', true],
            'uisRepo' => ['privates', 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository', 'getUtilisateurInstitutionSessionModuleRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'utilisateur' => 'App\\Entity\\Utilisateur',
            'uisRepo' => 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository',
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\InstitutionController::liste()', $container);
    }
}
