<?php

namespace ContainerRxXGSEN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionModuleControllermodifierInstitutionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6pPFRks.App\Controller\SessionModuleController::modifierInstitution()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6pPFRks.App\\Controller\\SessionModuleController::modifierInstitution()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'institution' => ['privates', '.errored..service_locator.6pPFRks.App\\Entity\\Institution', NULL, 'Cannot autowire service ".service_locator.6pPFRks": it needs an instance of "App\\Entity\\Institution" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'institution' => 'App\\Entity\\Institution',
            'em' => '?',
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\SessionModuleController::modifierInstitution()', $container);
    }
}
