<?php

namespace ContainerRxXGSEN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionModuleTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SessionModuleType' shared autowired service.
     *
     * @return \App\Form\SessionModuleType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SessionModuleType.php';

        return $container->privates['App\\Form\\SessionModuleType'] = new \App\Form\SessionModuleType();
    }
}
