<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Utilisateur__CLASSMETADATA__' => 0,
'App__Entity__Session__CLASSMETADATA__' => 1,
'App__Entity__Institution__CLASSMETADATA__' => 2,
'App__Entity__FormContact__CLASSMETADATA__' => 3,
'App__Entity__Invitation__CLASSMETADATA__' => 4,
'App__Entity__JourHoraire__CLASSMETADATA__' => 5,
'App__Entity__Module__CLASSMETADATA__' => 6,
'App__Entity__SessionModule__CLASSMETADATA__' => 7,
'App__Entity__StripePayment__CLASSMETADATA__' => 8,
'App__Entity__UtilisateurInstitutionSessionModule__CLASSMETADATA__' => 9,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Utilisateur',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Utilisateur',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UtilisateurRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'prenom' => [
                            'fieldName' => 'prenom',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'prenom',
                        ],
                        'nom' => [
                            'fieldName' => 'nom',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nom',
                        ],
                        'courriel' => [
                            'fieldName' => 'courriel',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => true,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'courriel',
                        ],
                        'motdepasse' => [
                            'fieldName' => 'motdepasse',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'motdepasse',
                        ],
                        'roles' => [
                            'fieldName' => 'roles',
                            'type' => 'json',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'roles',
                        ],
                        'commentaire' => [
                            'fieldName' => 'commentaire',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'commentaire',
                        ],
                        'note' => [
                            'fieldName' => 'note',
                            'type' => 'decimal',
                            'scale' => 2,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 5,
                            'columnName' => 'note',
                        ],
                        'telephone' => [
                            'fieldName' => 'telephone',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 20,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'telephone',
                        ],
                        'dateNaissance' => [
                            'fieldName' => 'dateNaissance',
                            'type' => 'date',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'date_naissance',
                        ],
                        'nombreSouscriptions' => [
                            'fieldName' => 'nombreSouscriptions',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nombre_souscriptions',
                        ],
                        'dateFinAbonnement' => [
                            'fieldName' => 'dateFinAbonnement',
                            'type' => 'datetime',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'date_fin_abonnement',
                        ],
                        'nombreInvitations' => [
                            'fieldName' => 'nombreInvitations',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'options' => [
                                'default' => 0,
                            ],
                            'columnName' => 'nombre_invitations',
                        ],
                        'dateCreation' => [
                            'fieldName' => 'dateCreation',
                            'type' => 'datetime_immutable',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'date_creation',
                        ],
                        'nombreInstitutions' => [
                            'fieldName' => 'nombreInstitutions',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nombre_institutions',
                        ],
                        'abonnementType' => [
                            'fieldName' => 'abonnementType',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'abonnement_type',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'prenom' => 'prenom',
                        'nom' => 'nom',
                        'courriel' => 'courriel',
                        'motdepasse' => 'motdepasse',
                        'roles' => 'roles',
                        'commentaire' => 'commentaire',
                        'note' => 'note',
                        'telephone' => 'telephone',
                        'date_naissance' => 'dateNaissance',
                        'nombre_souscriptions' => 'nombreSouscriptions',
                        'date_fin_abonnement' => 'dateFinAbonnement',
                        'nombre_invitations' => 'nombreInvitations',
                        'date_creation' => 'dateCreation',
                        'nombre_institutions' => 'nombreInstitutions',
                        'abonnement_type' => 'abonnementType',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'prenom' => 'prenom',
                        'nom' => 'nom',
                        'courriel' => 'courriel',
                        'motdepasse' => 'motdepasse',
                        'roles' => 'roles',
                        'commentaire' => 'commentaire',
                        'note' => 'note',
                        'telephone' => 'telephone',
                        'dateNaissance' => 'date_naissance',
                        'nombreSouscriptions' => 'nombre_souscriptions',
                        'dateFinAbonnement' => 'date_fin_abonnement',
                        'nombreInvitations' => 'nombre_invitations',
                        'dateCreation' => 'date_creation',
                        'nombreInstitutions' => 'nombre_institutions',
                        'abonnementType' => 'abonnement_type',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'utilisateur',
                        'indexes' => [
                            'idx_prenom' => [
                                'columns' => [
                                    'prenom',
                                ],
                            ],
                            'idx_nom' => [
                                'columns' => [
                                    'nom',
                                ],
                            ],
                            'idx_courriel' => [
                                'columns' => [
                                    'courriel',
                                ],
                            ],
                            'idx_commentaire' => [
                                'columns' => [
                                    'commentaire',
                                ],
                            ],
                            'idx_note' => [
                                'columns' => [
                                    'note',
                                ],
                            ],
                            'idx_telephone' => [
                                'columns' => [
                                    'telephone',
                                ],
                            ],
                            'idx_date_naissance' => [
                                'columns' => [
                                    'date_naissance',
                                ],
                            ],
                        ],
                    ],
                ],
                'associationMappings' => [
                    [
                        'institution' => [
                            'fieldName' => 'institution',
                            'joinColumns' => [
                                [
                                    'name' => 'institution_id',
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'utilisateurs',
                            'targetEntity' => 'App\\Entity\\Institution',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Utilisateur',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'institution_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'institution_id' => 'institution_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'institution_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'utilisateur_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'utilisateur_id_seq',
            ],
        ]
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Session',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Session',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\SessionRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'nom' => [
                            'fieldName' => 'nom',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nom',
                        ],
                        'type' => [
                            'fieldName' => 'type',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'type',
                        ],
                        'date_debut' => [
                            'fieldName' => 'date_debut',
                            'type' => 'date',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'date_debut',
                        ],
                        'date_fin' => [
                            'fieldName' => 'date_fin',
                            'type' => 'date',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'date_fin',
                        ],
                        'description' => [
                            'fieldName' => 'description',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'description',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'nom',
                        'type' => 'type',
                        'date_debut' => 'date_debut',
                        'date_fin' => 'date_fin',
                        'description' => 'description',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'nom',
                        'type' => 'type',
                        'date_debut' => 'date_debut',
                        'date_fin' => 'date_fin',
                        'description' => 'description',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'session',
                        'indexes' => [
                            'idx_nom' => [
                                'columns' => [
                                    'nom',
                                ],
                            ],
                            'idx_type' => [
                                'columns' => [
                                    'type',
                                ],
                            ],
                            'idx_date_debut' => [
                                'columns' => [
                                    'date_debut',
                                ],
                            ],
                            'idx_date_fin' => [
                                'columns' => [
                                    'date_fin',
                                ],
                            ],
                            'idx_description' => [
                                'columns' => [
                                    'description',
                                ],
                            ],
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
            'Doctrine\\ORM\\Id\\IdentityGenerator' => [
                'sequenceName' => [
                    1 => 'session_id_seq',
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Institution',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Institution',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\InstitutionRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'nom' => [
                            'fieldName' => 'nom',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nom',
                        ],
                        'adresse' => [
                            'fieldName' => 'adresse',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'adresse',
                        ],
                        'telephone' => [
                            'fieldName' => 'telephone',
                            'type' => 'bigint',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'telephone',
                        ],
                        'courriel' => [
                            'fieldName' => 'courriel',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'courriel',
                        ],
                        'createurId' => [
                            'fieldName' => 'createurId',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'cree_par_id',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'nom',
                        'adresse' => 'adresse',
                        'telephone' => 'telephone',
                        'courriel' => 'courriel',
                        'cree_par_id' => 'createurId',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'nom',
                        'adresse' => 'adresse',
                        'telephone' => 'telephone',
                        'courriel' => 'courriel',
                        'createurId' => 'cree_par_id',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'institution',
                        'indexes' => [
                            'idx_nom' => [
                                'columns' => [
                                    'nom',
                                ],
                            ],
                            'idx_adresse' => [
                                'columns' => [
                                    'adresse',
                                ],
                            ],
                            'idx_telephone' => [
                                'columns' => [
                                    'telephone',
                                ],
                            ],
                            'idx_courriel' => [
                                'columns' => [
                                    'courriel',
                                ],
                            ],
                        ],
                    ],
                ],
                'associationMappings' => [
                    [
                        'utilisateurs' => [
                            'fieldName' => 'utilisateurs',
                            'mappedBy' => 'institution',
                            'targetEntity' => 'App\\Entity\\Utilisateur',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\Institution',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'institution_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'institution_id_seq',
            ],
        ]
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\FormContact',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\FormContact',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\FormContactRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'Prenom' => [
                            'fieldName' => 'Prenom',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 25,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'prenom',
                        ],
                        'Nom' => [
                            'fieldName' => 'Nom',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 25,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nom',
                        ],
                        'Email' => [
                            'fieldName' => 'Email',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 50,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'email',
                        ],
                        'NomInstitution' => [
                            'fieldName' => 'NomInstitution',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 50,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nom_institution',
                        ],
                        'NomSession' => [
                            'fieldName' => 'NomSession',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 50,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nom_session',
                        ],
                        'NomModule' => [
                            'fieldName' => 'NomModule',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 50,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nom_module',
                        ],
                        'Dates' => [
                            'fieldName' => 'Dates',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 25,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'dates',
                        ],
                        'offre' => [
                            'fieldName' => 'offre',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 25,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'offre',
                        ],
                        'message' => [
                            'fieldName' => 'message',
                            'type' => 'text',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'message',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'prenom' => 'Prenom',
                        'nom' => 'Nom',
                        'email' => 'Email',
                        'nom_institution' => 'NomInstitution',
                        'nom_session' => 'NomSession',
                        'nom_module' => 'NomModule',
                        'dates' => 'Dates',
                        'offre' => 'offre',
                        'message' => 'message',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Prenom' => 'prenom',
                        'Nom' => 'nom',
                        'Email' => 'email',
                        'NomInstitution' => 'nom_institution',
                        'NomSession' => 'nom_session',
                        'NomModule' => 'nom_module',
                        'Dates' => 'dates',
                        'offre' => 'offre',
                        'message' => 'message',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'form_contact',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'form_contact_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'form_contact_id_seq',
            ],
        ]
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Invitation',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Invitation',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\InvitationRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'email' => [
                            'fieldName' => 'email',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'email',
                        ],
                        'token' => [
                            'fieldName' => 'token',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 32,
                            'unique' => true,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'token',
                        ],
                        'expireLe' => [
                            'fieldName' => 'expireLe',
                            'type' => 'datetime_immutable',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'expire_le',
                        ],
                        'creeLe' => [
                            'fieldName' => 'creeLe',
                            'type' => 'datetime_immutable',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'cree_le',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'email' => 'email',
                        'token' => 'token',
                        'expire_le' => 'expireLe',
                        'cree_le' => 'creeLe',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'email' => 'email',
                        'token' => 'token',
                        'expireLe' => 'expire_le',
                        'creeLe' => 'cree_le',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'invitation',
                    ],
                ],
                'lifecycleCallbacks' => [
                    [
                        'prePersist' => [
                            'setTimestamps',
                        ],
                    ],
                ],
                'associationMappings' => [
                    [
                        'institution' => [
                            'fieldName' => 'institution',
                            'joinColumns' => [
                                [
                                    'name' => 'institution_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\Institution',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Invitation',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'institution_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'institution_id' => 'institution_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'institution_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                        'invitedBy' => [
                            'fieldName' => 'invitedBy',
                            'joinColumns' => [
                                [
                                    'name' => 'invited_by_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => 'CASCADE',
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'invitationsSent',
                            'targetEntity' => 'App\\Entity\\Utilisateur',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Invitation',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'invited_by_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'invited_by_id' => 'invited_by_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'invited_by_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'invitation_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'invitation_id_seq',
            ],
        ]
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\JourHoraire',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\JourHoraire',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\JourHoraireRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'jour' => [
                            'fieldName' => 'jour',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 10,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'jour',
                        ],
                        'datePrecise' => [
                            'fieldName' => 'datePrecise',
                            'type' => 'date',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'date_precise',
                        ],
                        'heureDebut' => [
                            'fieldName' => 'heureDebut',
                            'type' => 'time',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'heure_debut',
                        ],
                        'heureFin' => [
                            'fieldName' => 'heureFin',
                            'type' => 'time',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'heure_fin',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'jour' => 'jour',
                        'date_precise' => 'datePrecise',
                        'heure_debut' => 'heureDebut',
                        'heure_fin' => 'heureFin',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'jour' => 'jour',
                        'datePrecise' => 'date_precise',
                        'heureDebut' => 'heure_debut',
                        'heureFin' => 'heure_fin',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'jour_horaire',
                    ],
                ],
                'associationMappings' => [
                    [
                        'utilisateurinstitutionsessionmodule' => [
                            'fieldName' => 'utilisateurinstitutionsessionmodule',
                            'joinColumns' => [
                                [
                                    'name' => 'institution_session_module_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'horaires',
                            'targetEntity' => 'App\\Entity\\UtilisateurInstitutionSessionModule',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\JourHoraire',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'institution_session_module_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'institution_session_module_id' => 'institution_session_module_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'institution_session_module_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'jour_horaire_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'jour_horaire_id_seq',
            ],
        ]
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Module',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Module',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ModuleRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'nom' => [
                            'fieldName' => 'nom',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nom',
                        ],
                        'description' => [
                            'fieldName' => 'description',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'description',
                        ],
                        'commentaire' => [
                            'fieldName' => 'commentaire',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'commentaire',
                        ],
                        'date_debut' => [
                            'fieldName' => 'date_debut',
                            'type' => 'date',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'date_debut',
                        ],
                        'date_fin' => [
                            'fieldName' => 'date_fin',
                            'type' => 'date',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'date_fin',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'nom',
                        'description' => 'description',
                        'commentaire' => 'commentaire',
                        'date_debut' => 'date_debut',
                        'date_fin' => 'date_fin',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'nom',
                        'description' => 'description',
                        'commentaire' => 'commentaire',
                        'date_debut' => 'date_debut',
                        'date_fin' => 'date_fin',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'module',
                        'indexes' => [
                            'idx_nom' => [
                                'columns' => [
                                    'nom',
                                ],
                            ],
                            'idx_description' => [
                                'columns' => [
                                    'description',
                                ],
                            ],
                            'idx_commentaire' => [
                                'columns' => [
                                    'commentaire',
                                ],
                            ],
                            'idx_date_debut_module' => [
                                'columns' => [
                                    'date_debut',
                                ],
                            ],
                            'idx_date_fin_module' => [
                                'columns' => [
                                    'date_fin',
                                ],
                            ],
                        ],
                    ],
                ],
                'associationMappings' => [
                    [
                        'sessionModules' => [
                            'fieldName' => 'sessionModules',
                            'mappedBy' => 'module',
                            'targetEntity' => 'App\\Entity\\SessionModule',
                            'cascade' => [
                                'persist',
                                'remove',
                            ],
                            'orphanRemoval' => true,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\Module',
                            'isCascadeRemove' => true,
                            'isCascadePersist' => true,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'module_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'module_id_seq',
            ],
        ]
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\SessionModule',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\SessionModule',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\SessionModuleRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'session_module',
                        'indexes' => [
                            'idx_session_id' => [
                                'columns' => [
                                    'session_id',
                                ],
                            ],
                            'idx_module_id' => [
                                'columns' => [
                                    'module_id',
                                ],
                            ],
                            'idx_institution_id' => [
                                'columns' => [
                                    'institution_id',
                                ],
                            ],
                        ],
                    ],
                ],
                'associationMappings' => [
                    [
                        'userAssociations' => [
                            'fieldName' => 'userAssociations',
                            'mappedBy' => 'sessionModule',
                            'targetEntity' => 'App\\Entity\\UtilisateurInstitutionSessionModule',
                            'cascade' => [
                                'persist',
                                'remove',
                            ],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\SessionModule',
                            'isCascadeRemove' => true,
                            'isCascadePersist' => true,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                        'module' => [
                            'fieldName' => 'module',
                            'joinColumns' => [
                                [
                                    'name' => 'module_id',
                                    'unique' => false,
                                    'nullable' => true,
                                    'onDelete' => 'CASCADE',
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'sessionModules',
                            'targetEntity' => 'App\\Entity\\Module',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\SessionModule',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'module_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'module_id' => 'module_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'module_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                        'session' => [
                            'fieldName' => 'session',
                            'joinColumns' => [
                                [
                                    'name' => 'session_id',
                                    'unique' => false,
                                    'nullable' => true,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\Session',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\SessionModule',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'session_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'session_id' => 'session_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'session_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                        'institution' => [
                            'fieldName' => 'institution',
                            'joinColumns' => [
                                [
                                    'name' => 'institution_id',
                                    'unique' => false,
                                    'nullable' => true,
                                    'onDelete' => null,
                                    'columnDefinition' => 'INT NOT NULL',
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\Institution',
                            'fetch' => 3,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\SessionModule',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'institution_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'institution_id' => 'institution_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'institution_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                        'horaires' => [
                            'fieldName' => 'horaires',
                            'mappedBy' => 'sessionModule',
                            'targetEntity' => 'App\\Entity\\JourHoraire',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\SessionModule',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'session_module_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'session_module_id_seq',
            ],
        ]
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\StripePayment',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\StripePayment',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\StripePaymentRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'paymentIntentId' => [
                            'fieldName' => 'paymentIntentId',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'payment_intent_id',
                        ],
                        'amount' => [
                            'fieldName' => 'amount',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'amount',
                        ],
                        'currency' => [
                            'fieldName' => 'currency',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'currency',
                        ],
                        'status' => [
                            'fieldName' => 'status',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'status',
                        ],
                        'createdAt' => [
                            'fieldName' => 'createdAt',
                            'type' => 'datetime_immutable',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'created_at',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'payment_intent_id' => 'paymentIntentId',
                        'amount' => 'amount',
                        'currency' => 'currency',
                        'status' => 'status',
                        'created_at' => 'createdAt',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'paymentIntentId' => 'payment_intent_id',
                        'amount' => 'amount',
                        'currency' => 'currency',
                        'status' => 'status',
                        'createdAt' => 'created_at',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'stripe_payment',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'stripe_payment_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'stripe_payment_id_seq',
            ],
        ]
    );
},
9 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\UtilisateurInstitutionSessionModule',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\UtilisateurInstitutionSessionModule',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UtilisateurInstitutionSessionModuleRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'commentaire_module' => [
                            'fieldName' => 'commentaire_module',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'commentaire_module',
                        ],
                        'note_module' => [
                            'fieldName' => 'note_module',
                            'type' => 'float',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'note_module',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'commentaire_module' => 'commentaire_module',
                        'note_module' => 'note_module',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'commentaire_module' => 'commentaire_module',
                        'note_module' => 'note_module',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'utilisateur_institution_session_module',
                        'indexes' => [
                            'idx_commentaire_module' => [
                                'columns' => [
                                    'commentaire_module',
                                ],
                            ],
                            'idx_note_module' => [
                                'columns' => [
                                    'note_module',
                                ],
                            ],
                            'idx_utilisateur_id' => [
                                'columns' => [
                                    'utilisateur_id',
                                ],
                            ],
                            'idx_session_module_id' => [
                                'columns' => [
                                    'session_module_id',
                                ],
                            ],
                        ],
                    ],
                ],
                'associationMappings' => [
                    [
                        'utilisateur' => [
                            'fieldName' => 'utilisateur',
                            'joinColumns' => [
                                [
                                    'name' => 'utilisateur_id',
                                    'unique' => false,
                                    'nullable' => true,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\Utilisateur',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\UtilisateurInstitutionSessionModule',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'utilisateur_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'utilisateur_id' => 'utilisateur_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'utilisateur_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                        'sessionModule' => [
                            'fieldName' => 'sessionModule',
                            'joinColumns' => [
                                [
                                    'name' => 'session_module_id',
                                    'unique' => false,
                                    'nullable' => true,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\SessionModule',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\UtilisateurInstitutionSessionModule',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'session_module_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'session_module_id' => 'session_module_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'session_module_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'utilisateur_institution_session_module_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'utilisateur_institution_session_module_id_seq',
            ],
        ]
    );
},

]];
