<?php

namespace ContainerQTwWh2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccueilControllerindexService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ZmozSE3.App\Controller\AccueilController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZmozSE3.App\\Controller\\AccueilController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'institutionRepository' => ['privates', 'App\\Repository\\InstitutionRepository', 'getInstitutionRepositoryService', true],
            'sessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
            'moduleRepository' => ['privates', 'App\\Repository\\ModuleRepository', 'getModuleRepositoryService', true],
            'formContactRepository' => ['privates', 'App\\Repository\\FormContactRepository', 'getFormContactRepositoryService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'institutionRepository' => 'App\\Repository\\InstitutionRepository',
            'sessionRepository' => 'App\\Repository\\SessionRepository',
            'moduleRepository' => 'App\\Repository\\ModuleRepository',
            'formContactRepository' => 'App\\Repository\\FormContactRepository',
            'mailer' => '?',
            'logger' => '?',
            'em' => '?',
        ]))->withContext('App\\Controller\\AccueilController::index()', $container);
    }
}
