<?php

namespace ContainerQTwWh2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthentificationService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\Authentification' shared autowired service.
     *
     * @return \App\Security\Authentification
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\Authentification'] = new \App\Security\Authentification(($container->services['router'] ?? self::getRouterService($container)));
    }
}
