<?php

namespace ContainerQTwWh2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbonnementService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\EventSubscriber\Abonnement' shared autowired service.
     *
     * @return \App\EventSubscriber\Abonnement
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\EventSubscriber\\Abonnement'] = new \App\EventSubscriber\Abonnement(($container->services['router'] ?? self::getRouterService($container)));
    }
}
