<?php

namespace ContainerQTwWh2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstitutionCreationTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\InstitutionCreationType' shared autowired service.
     *
     * @return \App\Form\InstitutionCreationType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\InstitutionCreationType'] = new \App\Form\InstitutionCreationType();
    }
}
