<?php

namespace ContainerQTwWh2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvitationRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\InvitationRepository' shared autowired service.
     *
     * @return \App\Repository\InvitationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\InvitationRepository'] = new \App\Repository\InvitationRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
