<?php

namespace ContainerQTwWh2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvitationControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\InvitationController' shared autowired service.
     *
     * @return \App\Controller\InvitationController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\InvitationController'] = $instance = new \App\Controller\InvitationController(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\InvitationController', $container));

        return $instance;
    }
}
