<?php

namespace ContainerQTwWh2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPdfGenerateurService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\PdfGenerateur' shared autowired service.
     *
     * @return \App\Service\PdfGenerateur
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\PdfGenerateur'] = new \App\Service\PdfGenerateur();
    }
}
