<?php

namespace ContainerQTwWh2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPDFEnvoieMailhandlePdfRequestService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.1483v_I.App\Controller\PDF_Envoie_Mail::handlePdfRequest()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1483v_I.App\\Controller\\PDF_Envoie_Mail::handlePdfRequest()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'utilisateur' => ['privates', 'App\\Entity\\Utilisateur', 'getUtilisateurService', true],
            'uisRepo' => ['privates', 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository', 'getUtilisateurInstitutionSessionModuleRepositoryService', true],
            'pdfGenerateur' => ['privates', 'App\\Service\\PdfGenerateur', 'getPdfGenerateurService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'utilisateur' => 'App\\Entity\\Utilisateur',
            'uisRepo' => 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository',
            'pdfGenerateur' => 'App\\Service\\PdfGenerateur',
            'mailer' => '?',
            'em' => '?',
        ]))->withContext('App\\Controller\\PDF_Envoie_Mail::handlePdfRequest()', $container);
    }
}
