<?php

namespace ContainerQTwWh2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionModuleRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SessionModuleRepository' shared autowired service.
     *
     * @return \App\Repository\SessionModuleRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SessionModuleRepository'] = new \App\Repository\SessionModuleRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
