<?php

namespace ContainerOKZF9ys;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstitutionTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\InstitutionType' shared autowired service.
     *
     * @return \App\Form\InstitutionType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\InstitutionType'] = new \App\Form\InstitutionType();
    }
}
