<?php

namespace ContainerOKZF9ys;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJourHoraireRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Repository\JourHoraireRepository' shared autowired service.
     *
     * @return \App\Repository\JourHoraireRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\JourHoraireRepository'] = new \App\Repository\JourHoraireRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
