<?php

namespace ContainerOKZF9ys;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLimiter_PdfGenerationCourtService extends App_KernelDevContainer
{
    /*
     * Gets the private 'limiter.pdf_generation_court' shared service.
     *
     * @return \Symfony\Component\RateLimiter\RateLimiterFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['limiter.pdf_generation_court'] = new \Symfony\Component\RateLimiter\RateLimiterFactory(['policy' => 'fixed_window', 'limit' => 1, 'interval' => '1 minute', 'id' => 'pdf_generation_court'], new \Symfony\Component\RateLimiter\Storage\CacheStorage(($container->services['cache.rate_limiter'] ?? $container->load('getCache_RateLimiterService'))), ($container->privates['lock.default.factory'] ?? $container->load('getLock_Default_FactoryService')));
    }
}
