<?php

namespace ContainerOKZF9ys;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPDFEnvoieMailenvoiToutPdfsService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.qqJ6CEo.App\Controller\PDF_Envoie_Mail::envoiToutPdfs()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qqJ6CEo.App\\Controller\\PDF_Envoie_Mail::envoiToutPdfs()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'utilisateurRepo' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
            'uisRepo' => ['privates', 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository', 'getUtilisateurInstitutionSessionModuleRepositoryService', true],
            'pdfGenerateur' => ['privates', 'App\\Service\\PdfGenerateur', 'getPdfGenerateurService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'utilisateurRepo' => 'App\\Repository\\UtilisateurRepository',
            'uisRepo' => 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository',
            'pdfGenerateur' => 'App\\Service\\PdfGenerateur',
            'mailer' => '?',
            'em' => '?',
        ]))->withContext('App\\Controller\\PDF_Envoie_Mail::envoiToutPdfs()', $container);
    }
}
