<?php

namespace ContainerOKZF9ys;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionModuleControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\SessionModuleController' shared autowired service.
     *
     * @return \App\Controller\SessionModuleController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SessionModuleController'] = $instance = new \App\Controller\SessionModuleController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\SessionModuleController', $container));

        return $instance;
    }
}
