<?php

namespace ContainerOKZF9ys;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTime_DatetimeFormatterService extends App_KernelDevContainer
{
    /*
     * Gets the private 'time.datetime_formatter' shared service.
     *
     * @return \Knp\Bundle\TimeBundle\DateTimeFormatter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['time.datetime_formatter'] = new \Knp\Bundle\TimeBundle\DateTimeFormatter(($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
