<?php

namespace ContainerOKZF9ys;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateurInstitutionSessionModuleTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\UtilisateurInstitutionSessionModuleType' shared autowired service.
     *
     * @return \App\Form\UtilisateurInstitutionSessionModuleType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\UtilisateurInstitutionSessionModuleType'] = new \App\Form\UtilisateurInstitutionSessionModuleType();
    }
}
