<?php

namespace ContainerJXC5jNr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbonnementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\Abonnement' shared autowired service.
     *
     * @return \App\EventSubscriber\Abonnement
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'Abonnement.php';

        return $container->privates['App\\EventSubscriber\\Abonnement'] = new \App\EventSubscriber\Abonnement(($container->services['router'] ?? self::getRouterService($container)));
    }
}
