<?php

namespace ContainerJXC5jNr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendrierControllervoirCalendrierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0pJot0q.App\Controller\CalendrierController::voirCalendrier()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0pJot0q.App\\Controller\\CalendrierController::voirCalendrier()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jourHoraireRepository' => ['privates', 'App\\Repository\\JourHoraireRepository', 'getJourHoraireRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'jourHoraireRepository' => 'App\\Repository\\JourHoraireRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\CalendrierController::voirCalendrier()', $container);
    }
}
