<?php

namespace ContainerJXC5jNr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPDFEnvoieMailenvoiSessionPdfsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Js4HdLW.App\Controller\PDF_Envoie_Mail::envoiSessionPdfs()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Js4HdLW.App\\Controller\\PDF_Envoie_Mail::envoiSessionPdfs()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
            'uismRepo' => ['privates', 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository', 'getUtilisateurInstitutionSessionModuleRepositoryService', true],
            'pdfGenerateur' => ['privates', 'App\\Service\\PdfGenerateur', 'getPdfGenerateurService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'sessionRepository' => 'App\\Repository\\SessionRepository',
            'uismRepo' => 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository',
            'pdfGenerateur' => 'App\\Service\\PdfGenerateur',
            'mailer' => '?',
            'em' => '?',
        ]))->withContext('App\\Controller\\PDF_Envoie_Mail::envoiSessionPdfs()', $container);
    }
}
