<?php

namespace ContainerJXC5jNr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionModuleControllermodifierSessionModuleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LceDNDN.App\Controller\SessionModuleController::modifierSessionModule()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LceDNDN.App\\Controller\\SessionModuleController::modifierSessionModule()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sessionModuleRepository' => ['privates', 'App\\Repository\\SessionModuleRepository', 'getSessionModuleRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'sessionModuleRepository' => 'App\\Repository\\SessionModuleRepository',
            'em' => '?',
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\SessionModuleController::modifierSessionModule()', $container);
    }
}
