<?php

namespace ContainerJXC5jNr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionModuleControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..Vj_0Fk.App\Controller\SessionModuleController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..Vj_0Fk.App\\Controller\\SessionModuleController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ModuleRepository' => ['privates', 'App\\Repository\\ModuleRepository', 'getModuleRepositoryService', true],
            'SessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
            'InstitutionRepository' => ['privates', 'App\\Repository\\InstitutionRepository', 'getInstitutionRepositoryService', true],
            'sessionModuleRepository' => ['privates', 'App\\Repository\\SessionModuleRepository', 'getSessionModuleRepositoryService', true],
            'utilisateurInstitutionSessionModuleRepository' => ['privates', 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository', 'getUtilisateurInstitutionSessionModuleRepositoryService', true],
            'UtilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'ModuleRepository' => 'App\\Repository\\ModuleRepository',
            'SessionRepository' => 'App\\Repository\\SessionRepository',
            'InstitutionRepository' => 'App\\Repository\\InstitutionRepository',
            'sessionModuleRepository' => 'App\\Repository\\SessionModuleRepository',
            'utilisateurInstitutionSessionModuleRepository' => 'App\\Repository\\UtilisateurInstitutionSessionModuleRepository',
            'UtilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
            'em' => '?',
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\SessionModuleController::index()', $container);
    }
}
