<?php

namespace ContainerJXC5jNr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionModuleControllermodifierSessionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ynbETY9.App\Controller\SessionModuleController::modifierSession()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ynbETY9.App\\Controller\\SessionModuleController::modifierSession()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'session' => ['privates', '.errored..service_locator.ynbETY9.App\\Entity\\Session', NULL, 'Cannot autowire service ".service_locator.ynbETY9": it needs an instance of "App\\Entity\\Session" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'session' => 'App\\Entity\\Session',
            'em' => '?',
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\SessionModuleController::modifierSession()', $container);
    }
}
