<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOKZF9ys\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOKZF9ys/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerOKZF9ys.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerOKZF9ys\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerOKZF9ys\App_KernelDevContainer([
    'container.build_hash' => 'OKZF9ys',
    'container.build_id' => 'f582c940',
    'container.build_time' => 1752678860,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOKZF9ys');
