<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxXGSEN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxXGSEN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRxXGSEN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRxXGSEN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRxXGSEN\App_KernelDevDebugContainer([
    'container.build_hash' => 'RxXGSEN',
    'container.build_id' => 'c970177e',
    'container.build_time' => 1752509432,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxXGSEN');
