<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJXC5jNr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJXC5jNr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJXC5jNr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJXC5jNr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJXC5jNr\App_KernelDevDebugContainer([
    'container.build_hash' => 'JXC5jNr',
    'container.build_id' => 'b4d3cd5a',
    'container.build_time' => 1752675145,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJXC5jNr');
