<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UtilisateurInstitutionSessionModule extends \App\Entity\UtilisateurInstitutionSessionModule implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'commentaire_module' => [parent::class, 'commentaire_module', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'note_module' => [parent::class, 'note_module', null],
        "\0".parent::class."\0".'sessionModule' => [parent::class, 'sessionModule', null],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null],
        'commentaire_module' => [parent::class, 'commentaire_module', null],
        'id' => [parent::class, 'id', null],
        'note_module' => [parent::class, 'note_module', null],
        'sessionModule' => [parent::class, 'sessionModule', null],
        'utilisateur' => [parent::class, 'utilisateur', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
