<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SessionModule extends \App\Entity\SessionModule implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'horaires' => [parent::class, 'horaires', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'institution' => [parent::class, 'institution', null],
        "\0".parent::class."\0".'module' => [parent::class, 'module', null],
        "\0".parent::class."\0".'session' => [parent::class, 'session', null],
        "\0".parent::class."\0".'userAssociations' => [parent::class, 'userAssociations', null],
        'horaires' => [parent::class, 'horaires', null],
        'id' => [parent::class, 'id', null],
        'institution' => [parent::class, 'institution', null],
        'module' => [parent::class, 'module', null],
        'session' => [parent::class, 'session', null],
        'userAssociations' => [parent::class, 'userAssociations', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
