<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Module extends \App\Entity\Module implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'commentaire' => [parent::class, 'commentaire', null],
        "\0".parent::class."\0".'date_debut' => [parent::class, 'date_debut', null],
        "\0".parent::class."\0".'date_fin' => [parent::class, 'date_fin', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'sessionModules' => [parent::class, 'sessionModules', null],
        'commentaire' => [parent::class, 'commentaire', null],
        'date_debut' => [parent::class, 'date_debut', null],
        'date_fin' => [parent::class, 'date_fin', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'nom' => [parent::class, 'nom', null],
        'sessionModules' => [parent::class, 'sessionModules', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
