<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Institution extends \App\Entity\Institution implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null],
        "\0".parent::class."\0".'courriel' => [parent::class, 'courriel', null],
        "\0".parent::class."\0".'createurId' => [parent::class, 'createurId', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null],
        "\0".parent::class."\0".'utilisateurs' => [parent::class, 'utilisateurs', null],
        'adresse' => [parent::class, 'adresse', null],
        'courriel' => [parent::class, 'courriel', null],
        'createurId' => [parent::class, 'createurId', null],
        'id' => [parent::class, 'id', null],
        'nom' => [parent::class, 'nom', null],
        'telephone' => [parent::class, 'telephone', null],
        'utilisateurs' => [parent::class, 'utilisateurs', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
