<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'abonnementType' => [parent::class, 'abonnementType', null],
        "\0".parent::class."\0".'commentaire' => [parent::class, 'commentaire', null],
        "\0".parent::class."\0".'courriel' => [parent::class, 'courriel', null],
        "\0".parent::class."\0".'dateCreation' => [parent::class, 'dateCreation', null],
        "\0".parent::class."\0".'dateFinAbonnement' => [parent::class, 'dateFinAbonnement', null],
        "\0".parent::class."\0".'dateNaissance' => [parent::class, 'dateNaissance', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'institution' => [parent::class, 'institution', null],
        "\0".parent::class."\0".'motdepasse' => [parent::class, 'motdepasse', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'nombreInstitutions' => [parent::class, 'nombreInstitutions', null],
        "\0".parent::class."\0".'nombreInvitations' => [parent::class, 'nombreInvitations', null],
        "\0".parent::class."\0".'nombreSouscriptions' => [parent::class, 'nombreSouscriptions', null],
        "\0".parent::class."\0".'note' => [parent::class, 'note', null],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null],
        'abonnementType' => [parent::class, 'abonnementType', null],
        'commentaire' => [parent::class, 'commentaire', null],
        'courriel' => [parent::class, 'courriel', null],
        'dateCreation' => [parent::class, 'dateCreation', null],
        'dateFinAbonnement' => [parent::class, 'dateFinAbonnement', null],
        'dateNaissance' => [parent::class, 'dateNaissance', null],
        'id' => [parent::class, 'id', null],
        'institution' => [parent::class, 'institution', null],
        'motdepasse' => [parent::class, 'motdepasse', null],
        'nom' => [parent::class, 'nom', null],
        'nombreInstitutions' => [parent::class, 'nombreInstitutions', null],
        'nombreInvitations' => [parent::class, 'nombreInvitations', null],
        'nombreSouscriptions' => [parent::class, 'nombreSouscriptions', null],
        'note' => [parent::class, 'note', null],
        'prenom' => [parent::class, 'prenom', null],
        'roles' => [parent::class, 'roles', null],
        'telephone' => [parent::class, 'telephone', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
