<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Invitation extends \App\Entity\Invitation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'creeLe' => [parent::class, 'creeLe', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'expireLe' => [parent::class, 'expireLe', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'institution' => [parent::class, 'institution', null],
        "\0".parent::class."\0".'invitedBy' => [parent::class, 'invitedBy', null],
        "\0".parent::class."\0".'token' => [parent::class, 'token', null],
        'creeLe' => [parent::class, 'creeLe', null],
        'email' => [parent::class, 'email', null],
        'expireLe' => [parent::class, 'expireLe', null],
        'id' => [parent::class, 'id', null],
        'institution' => [parent::class, 'institution', null],
        'invitedBy' => [parent::class, 'invitedBy', null],
        'token' => [parent::class, 'token', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
